name: Test & Deploy
on:
    push:
      branches:
        - main
jobs:
    run-tests:
        name: run-tests
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Repo
                uses: actions/checkout@v3
            -   name: Use Python
                uses: actions/setup-python@v4
                with:
                    python-version: '3.9'
            -   name: Install make
                run: sudo apt install make -y
            -   name: Install Application Requirements
                run: make requirements
            -   name: Install Dev Dependencies
                run: make dev-setup
            -   name: Run Checks
                run: make run-checks